import PDFDocument from "pdfkit";
import { tickets, complianceRecords } from "@/db/schema";
import { db } from "@/db";
import { eq } from "drizzle-orm";

/**
 * Phase 48: Sovereign Ticket PDF Service (v1.8.5 - INDUSTRIAL)
 * Generates itemized, industrial-standard proof-of-recovery receipts.
 */
export class SovereignTicketPDF {
  public static async generate(ticketId: string): Promise<Buffer> {
    const [ticket] = await db.select().from(tickets).where(eq(tickets.id, ticketId)).limit(1);
    const [compliance] = await db.select().from(complianceRecords).where(eq(complianceRecords.ticketId, ticketId)).limit(1);

    if (!ticket) throw new Error("Ticket not found.");

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: "A4" });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", (err: Error) => reject(err));

      // Industrial Header
      doc.fontSize(25).font("Helvetica-Bold").text("HOKEOS RECOVERY TICKET", { align: "center" });
      doc.fontSize(10).font("Helvetica").text(`TICKET ID: ${ticket.id}`, { align: "center" });
      doc.moveDown();

      // Horizontal Rule
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      doc.moveDown();

      // Recovery Content (Industrial Standard)
      const tableTop = doc.y;
      doc.fontSize(12).font("Helvetica-Bold");
      doc.text("METRIC", 50, tableTop);
      doc.text("VALUE", 200, tableTop);
      doc.text("UNIT", 350, tableTop);

      doc.fontSize(10).font("Helvetica");
      const row1 = tableTop + 25;
      doc.text("GROSS WEIGHT", 50, row1);
      doc.text(ticket.grossWeight || "0.00", 200, row1);
      doc.text("LBS", 350, row1);

      const row2 = row1 + 20;
      doc.text("TARE WEIGHT", 50, row2);
      doc.text(ticket.tareWeight || "0.00", 200, row2);
      doc.text("LBS", 350, row2);

      const row3 = row2 + 20;
      doc.text("NET WEIGHT", 50, row3);
      const net = (parseFloat(ticket.grossWeight || "0") - parseFloat(ticket.tareWeight || "0")).toFixed(2);
      doc.font("Helvetica-Bold").text(net, 200, row3);
      doc.text("LBS", 350, row3);

      doc.moveDown(4);

      // Compliance Block (NMVTIS Data)
      if (compliance) {
        doc.fontSize(14).font("Helvetica-Bold").text("COMPLIANCE DATA (FEDERAL AUDIT READY)");
        doc.fontSize(10).font("Helvetica");
        doc.text(`VIN: ${compliance.vin || "N/A"}`);
        doc.text(`SELLER: ${compliance.sellerName || "N/A"}`);
        doc.text(`DISPOSITION: ${compliance.disposition || "RECOVERY_INTAKE"}`);
        doc.moveDown();
      }

      // Legal & Footer
      doc.fontSize(8).font("Helvetica-Oblique").text(
        "Certified non-repudiable audit trace generated by HokeOS v1.8.5. This ticket constitutes a sovereign record of industrial intake.",
        { align: "bottom", width: 500 }
      );

      // Finalize
      doc.end();
    });
  }
}
